version: "3.3"

services:
  mongo:
    container_name: mongo-gofr
    image: mongo:3.6
    ports:
      - "27017:27017"
    restart: always

  redis:
    container_name: redis-gofr
    image: redis
    ports:
      - "6379:6379"
    restart: always

  hearth:
    container_name: hearth-gofr
    image: intrahealth/hearth:latest
    environment:
      - mongodb__url=mongodb://mongo/hearth-dev
      - logger__level=warning
      - authentication__type=disabled
      # - idGenerator=uuidv4 <- setting from jembi/health, is untested
    ports:
      - "3447:3447"
    restart: always

  facility-recon:
    container_name: facility-recon
    image: openhie/facility-recon:latest
    environment: 
      - HEARTH_URL=http://hearth:3447 
      - REDIS_HOST=redis 
      - DB_HOST=mongo 
    ports:
      - "3000:3000"
    restart: always